# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 07:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AipDirectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=8)),
                ('office_type', models.CharField(max_length=5)),
                ('delivery_status', models.CharField(max_length=15)),
                ('division', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('circle', models.CharField(max_length=25)),
                ('taluk', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ConversionRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalConversionRates',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical conversion rates',
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalRedTokens',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('table_type', models.IntegerField()),
                ('table_pkid', models.IntegerField()),
                ('token', models.CharField(max_length=255)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2017, 9, 22, 12, 38, 27, 599914))),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical red tokens',
                'get_latest_by': 'history_date',
                'ordering': ('-history_date', '-history_id'),
            },
        ),
        migrations.CreateModel(
            name='PartnerFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_number', models.CharField(max_length=25)),
                ('name', models.CharField(default='test', max_length=250)),
                ('email', models.CharField(default='test', max_length=250)),
                ('mobile', models.BigIntegerField(default=9790584839)),
                ('reason', models.CharField(max_length=250)),
                ('attachment', models.ImageField(upload_to='feedback/%Y-%m-%d-%H-%M-%S')),
                ('description', models.TextField(max_length=1000)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_type', models.IntegerField()),
                ('table_pkid', models.IntegerField()),
                ('token', models.CharField(max_length=255)),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2017, 9, 22, 12, 38, 27, 599914))),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
